# Generated by Django 2.2.2 on 2019-06-13 20:00

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_clientprofile_employeeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('uui', models.UUIDField(default=uuid.uuid4, verbose_name='Insurance Type Unique ID')),
            ],
            options={
                'verbose_name': 'Insurance Type',
                'verbose_name_plural': 'Insurance Types',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(default=core.helpers.getUniqueId, max_length=10, verbose_name='Reference ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(default=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_insurance', to='accounts.ClientProfile')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.EmployeeProfile')),
                ('insurance_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.InsuranceType')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
                'ordering': ['-start_date', 'ref_id'],
            },
        ),
    ]
