# Generated by Django 2.2.2 on 2019-06-13 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20190613_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
