# Generated by Django 2.2.2 on 2019-06-13 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20190613_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='submit_date',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
