# Generated by Django 2.2.2 on 2019-06-20 21:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20190613_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='insurances'),
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
