# Generated by Django 2.2.2 on 2019-06-14 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sub_title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pages/img')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Main Page',
                'verbose_name_plural': 'Main Pages',
                'ordering': ['-title'],
            },
        ),
    ]
