# Generated by Django 2.2.2 on 2019-06-14 20:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
