# Generated by Django 2.2.2 on 2019-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Employee'), (3, 'Client')], default=3, help_text='Rank', max_length=15),
        ),
    ]
