# Generated by Django 2.2.2 on 2019-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190613_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Client', 'Client')], default='Client', help_text='Rank', max_length=15),
        ),
    ]
