# Generated by Django 2.2.2 on 2019-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_employeeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='tw_link',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='tw_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
