# Generated by Django 2.2.2 on 2019-06-13 20:28

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_clientprofile_employeeprofile'),
        ('insurance', '0005_auto_20190613_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(default=core.helpers.getUniqueId, max_length=36, verbose_name='Reference ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to='accounts.ClientProfile')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='insurance.Insurance')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-payment_date'],
            },
        ),
    ]
