# Generated by Django 2.2.2 on 2019-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='done',
            field=models.BooleanField(default=False, help_text='Mark of Succeful Transaction (Payment Recieved)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(help_text='Completed, Half Pay or other Status', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='summary',
            field=models.TextField(blank=True, help_text='Any Other Thought on the Transaction?', null=True),
        ),
    ]
