# Generated by Django 2.2.2 on 2019-06-13 20:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190613_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Any Other Thought on the Transaction?', null=True),
        ),
    ]
